# all values can be changed to your liking, provided you know what you are doing
services:
  ytflex:
    build: .
    container_name: ytflex
    restart: always
    ports:
      - "2002:2002"
    volumes:
      - /app/ytflex/:/app/mountpoint/
